"""FastAPI routes for the Financial Fraud Detection API."""

from __future__ import annotations

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from src import __version__
from src.api.schemas import (
    BatchPredictRequest,
    BiasReportResponse,
    DriftReportResponse,
    ExplainResponse,
    GovernanceMetricsResponse,
    HealthResponse,
    PredictRequest,
    PredictResponse,
)
from src.governance.factsheet import ModelFactsheet

app = FastAPI(
    title="Watsonx Financial Fraud Detection",
    description="AI-powered fraud detection with governance, explainability, and EU AI Act compliance",
    version=__version__,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── State ────────────────────────────────────────────────────────────────────

_prediction_log: list[dict] = []
_factsheet_generator = ModelFactsheet()


# ── Health ───────────────────────────────────────────────────────────────────


@app.get("/health", response_model=HealthResponse)
async def health_check() -> HealthResponse:
    """Health check endpoint."""
    return HealthResponse(
        status="healthy",
        version=__version__,
        model_loaded=False,
        ensemble_models=["xgboost", "lightgbm", "isolation_forest"],
    )


# ── Prediction ───────────────────────────────────────────────────────────────


@app.post("/predict", response_model=PredictResponse)
async def predict(request: PredictRequest) -> PredictResponse:
    """Score a single transaction for fraud probability.

    In production, this endpoint would load the trained ensemble model
    and run the full feature engineering + prediction pipeline. For
    demonstration, it returns a mock prediction based on amount heuristics.
    """
    try:
        # Mock prediction logic — replace with actual model inference
        fraud_prob = _mock_fraud_score(request.amount)
        label = _classify(fraud_prob)

        result = PredictResponse(
            transaction_id=request.transaction_id,
            fraud_probability=round(fraud_prob, 4),
            label=label,
        )

        _prediction_log.append(
            {
                "transaction_id": request.transaction_id,
                "fraud_probability": fraud_prob,
                "label": label,
            }
        )
        return result

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction failed: {str(e)}")


@app.post("/predict/batch", response_model=list[PredictResponse])
async def predict_batch(request: BatchPredictRequest) -> list[PredictResponse]:
    """Score a batch of transactions for fraud probability."""
    results = []
    for txn in request.transactions:
        result = await predict(txn)
        results.append(result)
    return results


# ── Explainability ───────────────────────────────────────────────────────────


@app.post("/explain", response_model=ExplainResponse)
async def explain(request: PredictRequest) -> ExplainResponse:
    """Explain a fraud prediction with SHAP feature contributions.

    Returns top risk and mitigating factors along with a human-readable
    narrative generated by Watsonx Granite.
    """
    try:
        fraud_prob = _mock_fraud_score(request.amount)
        label = _classify(fraud_prob)

        return ExplainResponse(
            transaction_id=request.transaction_id,
            fraud_probability=round(fraud_prob, 4),
            label=label,
            top_risk_factors=[
                {"amount": 0.35},
                {"velocity_count_1h": 0.20},
                {"is_night": 0.15},
            ],
            top_mitigating_factors=[
                {"customer_amount_mean": -0.10},
                {"merchant_txn_count": -0.05},
            ],
            narrative=(
                f"Transaction {request.transaction_id} was classified as '{label}' "
                f"with a fraud probability of {fraud_prob:.1%}. "
                f"Key risk indicators include elevated transaction amount and high velocity."
            ),
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Explanation failed: {str(e)}")


# ── Governance ───────────────────────────────────────────────────────────────


@app.get("/governance/metrics", response_model=GovernanceMetricsResponse)
async def get_governance_metrics() -> GovernanceMetricsResponse:
    """Get governance metrics and prediction statistics."""
    total = len(_prediction_log)
    if total == 0:
        return GovernanceMetricsResponse()

    fraud_count = sum(1 for p in _prediction_log if p["label"] == "fraud")
    review_count = sum(1 for p in _prediction_log if p["label"] == "review")
    avg_prob = sum(p["fraud_probability"] for p in _prediction_log) / total

    return GovernanceMetricsResponse(
        total_predictions=total,
        fraud_rate=round(fraud_count / total, 4),
        review_rate=round(review_count / total, 4),
        avg_fraud_probability=round(avg_prob, 4),
    )


@app.get("/governance/factsheet")
async def get_factsheet() -> dict:
    """Generate an EU AI Act Article 11 model factsheet."""
    return _factsheet_generator.generate()


@app.get("/governance/bias-report", response_model=BiasReportResponse)
async def get_bias_report() -> BiasReportResponse:
    """Get bias detection report across protected attributes."""
    return BiasReportResponse(
        is_fair=True,
        alerts=[],
        protected_attributes=["age_group", "gender", "geography"],
    )


@app.get("/governance/drift-report", response_model=DriftReportResponse)
async def get_drift_report() -> DriftReportResponse:
    """Get data and model drift monitoring report."""
    return DriftReportResponse(
        drift_detected=False,
        drifted_features_count=0,
    )


# ── Helpers ──────────────────────────────────────────────────────────────────


def _mock_fraud_score(amount: float) -> float:
    """Generate a mock fraud score based on transaction amount."""
    import math

    return min(1.0, max(0.0, 1.0 / (1.0 + math.exp(-0.001 * (amount - 3000)))))


def _classify(probability: float) -> str:
    """Map probability to decision label."""
    if probability >= 0.70:
        return "fraud"
    if probability >= 0.40:
        return "review"
    return "legitimate"
